name: "Push nginx docker images"
description: "Push nginx docker images for a list of platforms"

inputs:
  nginx_tag:
    description: "Tag / version number of nginx"
    required: true
  dockerpwd:
    description: "Password for docker hub"
    required: true
  mail_url:
    description: "Connection string for the smtp host"
    required: true
  mail_to:
    description: "Address to send email to"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        pattern: digest-*
        merge-multiple: true
        path: /tmp/digests
    - name: DEBUG1
      run: |
        ls -latr /tmp/digests
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "${{ github.repository_owner }}"
        password: "${{ inputs.dockerpwd }}"

    - name: Create manifest list and push
      working-directory: /tmp/digests
      run: |
        docker buildx imagetools create -t ${{ github.repository }}:${{ inputs.nginx_tag }} -t ${{ github.repository }}:latest \
          $(printf '${{ github.repository }}@sha256:%s ' *)
      shell: bash

    - name: Inspect image
      run: |
        docker buildx imagetools inspect '${{ github.repository }}:${{ inputs.nginx_tag }}'
      shell: bash

    - name: Notify by email
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{ inputs.mail_url }}
        subject: "Built new docker image: ${{ github.repository }}:${{ inputs.nginx_tag }}"
        to: ${{ inputs.mail_to }}
        from: GitHub action
        body: Build job of ${{github.repository}} completed successfully! Pushed new image with version tag ${{ inputs.nginx_tag }}.
